### ISSUE TITLE
Cant Integration Doku Shopify

### ISSUE THREAD

**Issue by Linddy** [PTNUSASATUINTIARTHA-DOKU/DOKUShopify#1]
Dear GitHub,

I already follow step by step how to integration Doku merchant with my shopify store but when I checkout the link cant reach the DOKU Merchant and show ID Mall Empty

Please give me advice how to integrate
My shopify shop is : www.linddy.com

Thank you and I waiting for your reply.

Best Regards
![unnamed 1](https://user-images.githubusercontent.com/41106692/42724317-1eb14494-879a-11e8-8f0a-555c5d57e378.jpg)
![unnamed](https://user-images.githubusercontent.com/41106692/42724321-275ca444-879a-11e8-9688-f0b825038ed4.jpg)

**Comment by rudy-thong** [comment]
Hi,

looks like you haven't set the parameter x_account_id in your shopify store.
This x_account_id need to be filled with merchant ID generated by DOKU.
To get merchant ID, please kindly contact sales@doku.com.

Thank you.
